In [1]:
!mamba install pandas

import numpy as np
import pandas as pd
from pathlib import Path

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.7121999999284745 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [2]:
##MEDICINES TABLE:

medicines = [
    [1, "Dolo 650", "TABLET", 15, 3.00, 2.20],
    [2, "Paracetamol", "TABLET", 15, 2.00, 1.50],
    [3, "Aceclofenac", "TABLET", 10, 12.00, 7.50],
    [4, "Diclofenac", "TABLET", 10, 10.00, 6.50],
    [5, "Etoricoxib", "TABLET", 10, 18.00, 12.00],
    [6, "Naproxen", "TABLET", 10, 14.00, 9.00],
    [7, "Ibuprofen", "TABLET", 10, 5.00, 3.00],
    [8, "Thiocolchicoside", "TABLET", 10, 22.00, 15.00],
    [9, "Tizanidine", "TABLET", 10, 15.00, 9.50],
    [10, "Baclofen", "TABLET", 10, 16.00, 11.00],

    [11, "Pregabalin", "CAPSULE", 10, 30.00, 21.00],
    [12, "Gabapentin", "CAPSULE", 10, 35.00, 25.00],
    [13, "Methylcobalamin", "TABLET", 10, 25.00, 17.00],
    [14, "Calcium Citrate", "TABLET", 15, 12.00, 8.00],
    [15, "Shelcal 500", "TABLET", 15, 11.00, 7.00],
    [16, "Vitamin D3 60000 IU", "CAPSULE", 4, 30.00, 18.00],

    [17, "Pantoprazole", "TABLET", 15, 6.00, 3.50],
    [18, "Rabeprazole", "TABLET", 15, 7.00, 4.50],
    [19, "Omeprazole", "TABLET", 15, 5.00, 3.00],
    [20, "Antacid Syrup", "BOTTLE", None, 120.00, 80.00],

    [21, "Volini Gel", "TUBE", None, 110.00, 70.00],
    [22, "Dynapar Gel", "TUBE", None, 130.00, 85.00],
    [23, "Pain Relief Spray", "SPRAY", None, 180.00, 120.00],

    [24, "Trypsin Chymotrypsin", "TABLET", 10, 25.00, 18.00],
    [25, "Serratiopeptidase", "TABLET", 10, 20.00, 14.00],
    [26, "Calcitriol", "CAPSULE", 10, 28.00, 18.00],
    [27, "Vitamin B12", "TABLET", 10, 18.00, 12.00],
    [28, "Multivitamin", "TABLET", 15, 10.00, 6.00],

    [29, "Amoxicillin", "CAPSULE", 10, 12.00, 8.00],
    [30, "Cefixime", "TABLET", 10, 20.00, 14.00],
    [31, "Azithromycin", "TABLET", 3, 35.00, 25.00],

    [32, "Diclofenac Injection", "PIECE", None, 55.00, 35.00],
    [33, "Tramadol Injection", "PIECE", None, 80.00, 55.00],
    [34, "Vitamin B12 Injection", "PIECE", None, 65.00, 45.00],
    [35, "Methylprednisolone Injection", "PIECE", None, 150.00, 100.00],
    [36, "Hydrocortisone Injection", "PIECE", None, 120.00, 80.00],

    [37, "Crepe Bandage", "PIECE", None, 180.00, 120.00],
    [38, "Cotton Roll", "PIECE", None, 70.00, 45.00],
    [39, "Sterile Gauze Pack", "PIECE", None, 50.00, 30.00],
    [40, "Adhesive Tape", "PIECE", None, 40.00, 25.00]
]
medicine_df = pd.DataFrame(
    medicines,
    columns = [
        "medicine_id",
        "medicine_name",
        "unit_type",
        "tablets_per_piece",
        "selling_price_per_unit",
        "purchase_price_per_unit"
        
    ]
)
medicine_df

,medicine_id,medicine_name,unit_type,tablets_per_piece,purchase_price_per_unit,selling_price_per_unit
0,1,Dolo 650,TABLET,15.0,3.0,2.2
1,2,Paracetamol,TABLET,15.0,2.0,1.5
2,3,Aceclofenac,TABLET,10.0,12.0,7.5
3,4,Diclofenac,TABLET,10.0,10.0,6.5
4,5,Etoricoxib,TABLET,10.0,18.0,12.0
5,6,Naproxen,TABLET,10.0,14.0,9.0
6,7,Ibuprofen,TABLET,10.0,5.0,3.0
7,8,Thiocolchicoside,TABLET,10.0,22.0,15.0
8,9,Tizanidine,TABLET,10.0,15.0,9.5
9,10,Baclofen,TABLET,10.0,16.0,11.0
10,11,Pregabalin,CAPSULE,10.0,30.0,21.0
11,12,Gabapentin,CAPSULE,10.0,35.0,25.0
12,13,Methylcobalamin,TABLET,10.0,25.0,17.0
13,14,Calcium Citrate,TABLET,15.0,12.0,8.0
14,15,Shelcal 500,TABLET,15.0,11.0,7.0
15,16,Vitamin D3 60000 IU,CAPSULE,4.0,30.0,18.0
16,17,Pantoprazole,TABLET,15.0,6.0,3.5
17,18,Rabeprazole,TABLET,15.0,7.0,4.5
18,19,Omeprazole,TABLET,15.0,5.0,3.0
19,20,Antacid Syrup,BOTTLE,NaN,120.0,80.0
20,21,Volini Gel,TUBE,NaN,110.0,70.0
21,22,Dynapar Gel,TUBE,NaN,130.0,85.0
22,23,Pain Relief Spray,SPRAY,NaN,180.0,120.0
23,24,Trypsin Chymotrypsin,TABLET,10.0,25.0,18.0
24,25,Serratiopeptidase,TABLET,10.0,20.0,14.0
25,26,Calcitriol,CAPSULE,10.0,28.0,18.0
26,27,Vitamin B12,TABLET,10.0,18.0,12.0
27,28,Multivitamin,TABLET,15.0,10.0,6.0
28,29,Amoxicillin,CAPSULE,10.0,12.0,8.0
29,30,Cefixime,TABLET,10.0,20.0,14.0
30,31,Azithromycin,TABLET,3.0,35.0,25.0
31,32,Diclofenac Injection,PIECE,NaN,55.0,35.0
32,33,Tramadol Injection,PIECE,NaN,80.0,55.0
33,34,Vitamin B12 Injection,PIECE,NaN,65.0,45.0
34,35,Methylprednisolone Injection,PIECE,NaN,150.0,100.0
35,36,Hydrocortisone Injection,PIECE,NaN,120.0,80.0
36,37,Crepe Bandage,PIECE,NaN,180.0,120.0
37,38,Cotton Roll,PIECE,NaN,70.0,45.0
38,39,Sterile Gauze Pack,PIECE,NaN,50.0,30.0
39,40,Adhesive Tape,PIECE,NaN,40.0,25.0

In [3]:
##PATIENTS GENERATION

first_names = [
    "Rahul", "Amit", "Rajesh", "Vikram", "Ankit",
    "Rohit", "Arjun", "Karan", "Manish", "Sandeep",
    "Nitin", "Ajay", "Deepak", "Mohit", "Rakesh",
    "Priya", "Neha", "Pooja", "Anjali", "Sneha",
    "Kavita", "Ritu", "Shreya", "Megha", "Nidhi",
    "Aarti", "Preeti", "Swati", "Simran", "Rashmi",
    "Abhishek", "Aditya", "Yash", "Harsh", "Varun",
    "Riya", "Ishita", "Tanvi", "Muskan", "Khushi"
]

last_names = [
    "Sharma", "Verma", "Gupta", "Singh", "Patel",
    "Jain", "Agarwal", "Khanna", "Kapoor", "Malhotra",
    "Bansal", "Mehta", "Arora", "Chopra", "Saxena",
    "Yadav", "Mishra", "Pandey", "Tiwari", "Dubey",
    "Reddy", "Nair", "Iyer", "Menon", "Pillai",
    "Kulkarni", "Deshmukh", "Joshi", "Patil", "Shinde",
    "Bhatt", "Soni", "Chaudhary", "Kumar", "Thakur",
    "Sethi", "Goyal", "Mittal", "Bhatia", "Sinha"
]
pat_gender = ["M","F"]

num_patients=200
patient_names = [f"{np.random.choice(first_names)} {np.random.choice(last_names)}"
                for _ in range(num_patients)
                ]
patient_age = np.random.randint(low=18,high=82,size=num_patients)
patient_gender = np.random.choice(pat_gender,num_patients,p=[0.55,0.45])
patient_ids = list(range(1, num_patients + 1))

mobile_numbers = [
    f"9{str(i).zfill(9)}"
    for i in range(1, num_patients + 1)
]

patients_df = pd.DataFrame({
    "p_id": patient_ids,
    "p_name": patient_names,
    "p_age": patient_age,
    "p_gender": patient_gender,
    "mobile_number": mobile_numbers
})
patients_df

     patient_id        patient_name  age gender mobile_number
0             1     Khushi Malhotra   66      F    9000000001
1             2        Sneha Khanna   34      F    9000000002
2             3          Amit Patil   22      M    9000000003
3             4  Abhishek Chaudhary   38      M    9000000004
4             5         Priya Bhatt   60      F    9000000005
..          ...                 ...  ...    ...           ...
195         196     Rashmi Deshmukh   45      F    9000000196
196         197        Ishita Gupta   71      F    9000000197
197         198       Preeti Mittal   59      M    9000000198
198         199         Amit Tiwari   58      F    9000000199
199         200       Muskan Tiwari   63      F    9000000200

[200 rows x 5 columns]

In [4]:
# --------------------------------------------------
# Generate Dates
# --------------------------------------------------

dates = pd.date_range(
    start="2025-01-01",
    end="2025-12-31",
    freq="D"
)

# --------------------------------------------------
# Generate Daily Patient Counts
# --------------------------------------------------

daily_count = []

day_type = ["Slow", "Average", "Busy"]

for _ in dates:

    d = np.random.choice(
        day_type,
        p=[0.2, 0.5, 0.3]
    )

    if d == "Slow":
        count = np.random.randint(5, 10)

    elif d == "Average":
        count = np.random.randint(10, 20)

    else:
        count = np.random.randint(20, 35)

    daily_count.append(count)

# --------------------------------------------------
# Generate Visits
# --------------------------------------------------

all_patients = patients_df["patient_id"].tolist()

visits = []

visit_counter = 1

for date, patient_count in zip(dates, daily_count):

    today_patients = np.random.choice(
        all_patients,
        size=patient_count,
        replace=False
    )

    for patient in today_patients:

        # --------------------------
        # Consultation Fee
        # --------------------------

        consultation_fee = 400

        # Complimentary visit (~3%)
        if np.random.random() < 0.03:
            consultation_fee = 0

        # --------------------------
        # Medicine Amount
        # --------------------------

        medicine_amount = np.random.choice(
            [0, 50, 100, 150, 200, 250, 300, 400],
            p=[0.05, 0.10, 0.20, 0.20, 0.20, 0.15, 0.08, 0.02]
        )

        # --------------------------
        # Service Amount
        # --------------------------

        service_amount = 0

        if np.random.random() < 0.15:

            service_amount = np.random.choice(
                [100, 150, 250, 300, 600],
                p=[0.30, 0.25, 0.20, 0.15, 0.10]
            )

        # --------------------------
        # Payment Mode
        # --------------------------

        payment_mode = np.random.choice(
            ["CASH", "ONLINE"],
            p=[0.65, 0.35]
        )

        # --------------------------
        # Create Visit Record
        # --------------------------

        visits.append([
            visit_counter,
            patient,
            date,
            consultation_fee,
            medicine_amount,
            service_amount,
            payment_mode
        ])

        visit_counter += 1

# --------------------------------------------------
# Create DataFrame
# --------------------------------------------------

visits_df = pd.DataFrame(
    visits,
    columns=[
        "visit_id",
        "p_id",
        "visit_date",
        "consultation_fee",
        "medicine_amount",
        "service_amount",
        "payment_mode"
    ]
)

# Preview
visits_df

,visit_id,p_id,visit_date,consultation_fee,medicine_amount,service_amount,payment_mode
0,1,107,2025-01-01,400,200,0,CASH
1,2,110,2025-01-01,400,250,0,ONLINE
2,3,180,2025-01-01,400,200,600,CASH
3,4,108,2025-01-01,400,200,0,CASH
4,5,147,2025-01-01,400,250,0,CASH
...,...,...,...,...,...,...,...
6159,6160,104,2025-12-31,400,0,0,ONLINE
6160,6161,66,2025-12-31,400,200,0,ONLINE
6161,6162,74,2025-12-31,400,150,0,CASH
6162,6163,121,2025-12-31,400,100,0,ONLINE
6163,6164,191,2025-12-31,400,150,0,ONLINE

In [5]:
services = [
    ["A",300],
    ["C",250],
    ["B",150],
    ["D",200]
]

services_df = pd.DataFrame(
    services,
    columns = [
        "service_name",
        "service_cost"
    ]
)

services_df

  service_name  service_cost
0            A           300
1            C           250
2            B           150
3            D           200

In [6]:
# ==================================================
# MEDICINE PURCHASED DATA GENERATION
# ==================================================

purchases = []

purchase_id = 1

vendors = [
    "ABC Pharma",
    "HealthCare Distributors",
    "MediPlus",
    "Sharma Medical Agency",
    "LifeCare Suppliers"
]

high_frequency = [
    2,   # Paracetamol
    3,   # Aceclofenac
    4,   # Diclofenac
    5,   # Etoricoxib
    14,  # Calcium Citrate
    15,  # Shelcal 500
    16,  # Vitamin D3
    21,  # Volini Gel
    22   # Dynapar Gel
]

for medicine in medicine_df["medicine_id"]:

    # ---------------------------------
    # High-use medicines purchased more
    # frequently than rare medicines
    # ---------------------------------

    if medicine in high_frequency:

        num_orders = np.random.randint(25, 40)

    else:

        num_orders = np.random.randint(10, 20)

    purchase_dates = np.random.choice(
        dates,
        size=num_orders,
        replace=False
    )

    for date in purchase_dates:

        # ---------------------------------
        # High-use medicines bought
        # in larger quantities
        # ---------------------------------

        if medicine in high_frequency:

            quantity_strips = np.random.randint(
                300,
                800
            )

        else:

            quantity_strips = np.random.randint(
                50,
                250
            )

        tablets_per_strip = medicine_df.loc[
            medicine_df["medicine_id"] == medicine,
            "tablets_per_piece"
        ].iloc[0]

        if pd.notna(tablets_per_strip):

            quantity_purchased = (
                quantity_strips *
                tablets_per_strip
            )

        else:

            quantity_purchased = quantity_strips

        vendor_name = np.random.choice(vendors)

        purchase_price = medicine_df.loc[
            medicine_df["medicine_id"] == medicine,
            "purchase_price_per_unit"
        ].iloc[0]

        total_purchase_cost = (
            quantity_purchased *
            purchase_price
        )

        purchases.append([
            purchase_id,
            medicine,
            date,
            quantity_purchased,
            total_purchase_cost,
            vendor_name
        ])

        purchase_id += 1

# ==================================================
# Create DataFrame
# ==================================================

medicine_purchased_df = pd.DataFrame(
    purchases,
    columns=[
        "purchase_id",
        "medicine_id",
        "purchase_date",
        "quantity_purchased",
        "total_purchase_cost",
        "vendor_name"
    ]
)

medicine_purchased_df.head()

,purchase_id,medicine_id,purchase_date,quantity_purchased,total_purchase_cost,vendor_name
0,1,1,2025-10-23,3555.0,10665.0,LifeCare Suppliers
1,2,1,2025-12-03,1440.0,4320.0,HealthCare Distributors
2,3,1,2025-09-24,3510.0,10530.0,HealthCare Distributors
3,4,1,2025-12-02,1395.0,4185.0,HealthCare Distributors
4,5,1,2025-07-03,3255.0,9765.0,MediPlus

In [7]:
# ==================================================
# MEDICINE DISPENSED DATA GENERATION
# ==================================================

dispensed = []

dispense_id = 1

high_frequency = [
    2,   # Paracetamol
    3,   # Aceclofenac
    4,   # Diclofenac
    5,   # Etoricoxib
    14,  # Calcium Citrate
    15,  # Shelcal 500
    16,  # Vitamin D3
    21,  # Volini Gel
    22   # Dynapar Gel
]

all_medicines = medicine_df["medicine_id"].tolist()

for visit_id in visits_df["visit_id"]:

    # number of medicines prescribed
    medicine_count = np.random.choice(
        [0, 1, 2, 3, 4],
        p=[0.05, 0.20, 0.40, 0.25, 0.10]
    )

    if medicine_count == 0:
        continue

    selected_medicines = []

    for _ in range(medicine_count):

        # 70% chance of selecting common medicines
        if np.random.random() < 0.40:

            medicine = np.random.choice(
                high_frequency
            )

        else:

            medicine = np.random.choice(
                all_medicines
            )

        selected_medicines.append(medicine)

    # remove duplicates
    selected_medicines = list(
        set(selected_medicines)
    )

    for medicine in selected_medicines:

        unit_type = medicine_df.loc[
            medicine_df["medicine_id"] == medicine,
            "unit_type"
        ].iloc[0]

        if unit_type in ["TABLET", "CAPSULE"]:

            quantity_given = np.random.choice(
                [5, 10, 15, 20],
                p=[0.20, 0.40, 0.30, 0.10]
            )

        elif unit_type in ["TUBE", "SPRAY"]:

            quantity_given = 1

        else:

            quantity_given = np.random.choice(
                [1, 2]
            )

        dispensed.append([
            dispense_id,
            visit_id,
            medicine,
            quantity_given
        ])

        dispense_id += 1

medicine_dispensed_df = pd.DataFrame(
    dispensed,
    columns=[
        "dispense_id",
        "visit_id",
        "medicine_id",
        "quantity_given"
    ]
)

medicine_dispensed_df.head()

   dispense_id  visit_id  medicine_id  quantity_given
0            1         1           27               5
1            2         1            5              20
2            3         2           25              10
3            4         2           37               2
4            5         4           21               1

In [8]:
len(medicine_dispensed_df)

12766

In [9]:
purchased = (
    medicine_purchased_df
    .groupby("medicine_id")["quantity_purchased"]
    .sum()
)

dispensed = (
    medicine_dispensed_df
    .groupby("medicine_id")["quantity_given"]
    .sum()
)

inventory = purchased.subtract(
    dispensed,
    fill_value=0
)

inventory.sort_values().head(10)

medicine_id
40    1071.0
23    1154.0
36    1230.0
32    1231.0
39    1457.0
34    1485.0
38    1654.0
37    1690.0
20    1917.0
33    2086.0
dtype: float64

In [10]:
inventory.sort_values().head(15)

medicine_id
40     1071.0
23     1154.0
36     1230.0
32     1231.0
39     1457.0
34     1485.0
38     1654.0
37     1690.0
20     1917.0
33     2086.0
35     2380.0
31     5858.0
26    12090.0
10    12520.0
27    13040.0
dtype: float64

In [11]:
inventory.min()

(inventory < 0).sum()

np.int64(0)